apiVersion: v1
kind: ConfigMap
metadata:
  name: kappnav.status-mapping.liberty-app
  namespace: kappnav
data:
  algorithm: "function getStatus(status) { 

    var json= JSON.parse(status); 

    var statusText;
    if ( json.state == 'STARTED' ) 
      statusText='Normal';
    else
      statusText='Problem';

    var statusFlyover = 'state: ' + json.state; 
    
    //var nlsJSON= [ 'status.flyover.openliberty', json.state ]; 

    var statusJSON= { 'value': statusText, 'flyover': statusFlyover };

    return JSON.stringify(statusJSON); 
}"  